### ISSUE TITLE
User koopt property

### ISSUE THREAD

**Issue by YiikerGiiker** [Python-Project-Thomas-More-year-2/backend-flask-Python-Project-Thomas-More-year-2#20]
- bank stuurt request for payment
- user betaald (of niet)

- [x] Nieuw Model `Transaction` toevoegen
- [x] **POST** `/session/game/property-purchase`
  - [x] add route
  - [x] add schema
  - [x] check if user is logged in
  - [x] _assert_is_host_
  - [x] check if session has been started
  - [x] check if the given `transaction.request_payer` exists (and in same session) _(check given POST-data)_
  - [x] create transaction and store in database (`transaction.request_send = None`, **`None` = bank**)
  - [x] send _transaction-object_ to `transaction.request_payer`
  - [x] return `{}, 204` _#no content_

### Request
```json
{
  "user": {
    "id": <number>
  },
  "transaction": {
    "amount": <number>
  }
}
```

---

- [x] **PUT** `/session/game/property-purchase` _(The user pays for the required **transaction**, this is a reponse as the `transaction.request_payer` to the `transaction`)_
  - [x] add route
  - [x] add schema
  - [x] check if user is logged in
  - [x] check if the user is the `transaction.request_payer` of the given `transaction.id`
  - [x] check if user has enough money <ins>(What to do next i a big question **(TBD)**)</ins>
  - [x] `user.money - transaction.amount`, commit to db
  - [x] return `user, 200`

### Request
```json
{
  "transaction": {
    "id": <number>
  }
}
```

**Comment by LanderVanlaer** [comment]
![image](https://user-images.githubusercontent.com/25882462/208720378-209f1442-59aa-4185-b106-92f9605058a1.png)
